### ISSUE TITLE
Shell dont work on windows 

### ISSUE THREAD

**Issue by rubemlrm** [gbaptista/sublime-3-shell-exec#1]
When i'm trying run some commands dont work on windows and i get this message

``` python
create Popen: executable=powershell.exe --login
Exception in thread Thread-248:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "ShellExec in C:\Users\Rubem\AppData\Roaming\Sublime Text 3\Installed Packages\Shell Exec.sublime-package", line 161, in execute_shell_command
  File "./subprocess.py", line 748, in __init__
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr
```

**Comment by gbaptista** [comment]
@Rubemlrm I made some changes in version [0.0.8](https://github.com/gbaptista/sublime-3-shell-exec/releases/tag/0.0.8). Could you reinstall and try again, please?

**Comment by rubemlrm** [comment]
@gbaptista i will try that =)
